sudo: required
group: deprecated-2017Q3
language: scala
scala:
- 2.11.8
services:
- docker
before_install:
- "./tools/travis/setup.sh"
install: true
script:
- "./tools/travis/build.sh && ./tools/travis/deploy.sh && ./tools/travis/test.sh"
deploy:
- provider: script
  script: "./tools/travis/publish.sh ibmfunctions ${TRAVIS_TAG%@*} ${TRAVIS_TAG##*@}"
  on:
    tags: true
    all_branches: true
env:
  global:
  - secure: Nhexw05d6XTq7Rl05rDMaREBv5x5sD0hGH3QtPfM+Rgc9CeX/O5VLObX16Y5r9IP77X+G6mb4kn6NzPRc8ThXW35VMyONomgX7J12l31LmBKt7DWGAEvZ+WOx7yBB748q3L2u7g1U2EfDJMKlhyBXD5XrRJPhkpfjaTFoTb1wzl+1k9nPSAhDC8qqAJg9OjH53772XjXp4qnQXGwmmy0gfLxDGT3s6KzqbEYIwnC+UqEsjUDP2wLOwobDIPFHHY0NzUxKRACSWAONl0fI8103mYBoaM83ujxlBtZtwGu0STYGzmN2fhWUsLxzzWP3fmCHIQ5vi7RiLQRNrJWBHL2TdXyJ+rs7Llsf6nktgHgKILXcrDe4vatUPZtM5k5GINfzbtLgrcxVe6C3WcIowDsNNL4tN1lD/cJB4U+daSEvjRyVzTRD3eGfzinmZbAhi3xfMN/9ym6JaYlUaHTUcxxMaQ1lpYkxOCLkA8QdZ+kjOPyrfcZzPFvD59RTnDiJOGG+uybVnZ1/lSRWRKfvWtgGb9IwIO74JKxzPcWepl5I1cGkFstxz7i9nnCGaeAUvsze6joCqfI2oeaOSBl9PKTOerTCXirZhHCTS2GONDP1jCo2CKCXKXir50ACxN7H8m9yC0ockSahw+mGOzNqrSwTy8jJinGwCPuoF9lCEUTwWY=
  - secure: jyk83djIcS2uIuyrCWAZXUL8nxV8WxGuqMks1bvND/fo9YkwZkgLgYifBkhJtNE7qXfqJm6KgJSdOJGmD7Ivx4BxXhYaccwnboOAooJVmkDquDb53QDV7y5mYTHDSRiPUS0yTJRrorkh5U8od6strVWfEhRY7Rw68pRkNU0/nJhXZ8MRs4Q7klvBYeoQtOhkPLZmU8OlGUdXSXYPFflwyXnSYDA4MD+sARfUsQAbVVujz0GNMUCrD5vHRntc8SrHv2jR2IRDDpx8WuyHhHFPxS7g6+uA6V29fJx2dVnPau7mcXe37qQdqL/DE4HUhisIFnBQZnugpzhj3Q3zx05BNhApflvdlYdRo7KwkEHI4z2V3Vs0J/LRZk2ynjPY8wt8Up0YSmYCw326mZdudwHtKpuzNHhq/FuwH8HnMRrfXpTkrEO48yI+7j63+bCOEraqSpVjkD0E3HZ/JkiArTjol+Dqe3kVIk/ONU8Wnd+XDK6cQbhBS/5KrfexQqDuVbHc+SbU5Hqs+iNGSoeO2yXYs9FdxE4xo7wzWnE618Ihs202NYMcZGGXOdbENuHvf16f7oF0mIkOh/DMOcZn9pLAt4yfXUASpor0HvwXxu+kL+XoQ4vGd/OMMniq81LYsrkmc6rc1IsaCfox71+jcVhwad1IZbs3DevJnuQzyEmdApg=
